# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(130, 60)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.onButton = QtWidgets.QRadioButton(self.centralwidget)
        self.onButton.setEnabled(True)
        self.onButton.setGeometry(QtCore.QRect(20, 10, 82, 17))
        self.onButton.setObjectName("onButton")
        self.offButton = QtWidgets.QRadioButton(self.centralwidget)
        self.offButton.setGeometry(QtCore.QRect(20, 30, 82, 17))
        self.offButton.setObjectName("offButton")
        self.timerSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.timerSpinBox.setGeometry(QtCore.QRect(70, 20, 42, 22))
        self.timerSpinBox.setObjectName("timerSpinBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BT keep alive"))
        self.onButton.setText(_translate("MainWindow", "on"))
        self.offButton.setText(_translate("MainWindow", "off"))
